#selectPlatformName = mobile

#--------WebBrowser Input Data-----------

websiteUrl = https://www.flipkart.com
browserName = chrome
chromeDriverPath = /Drivers/chromedriver.exe
fireFoxDriverPath =
safariDriverPath = 

#-------login page--------
enterMobileNumber = 9857767833

#-------grocery page--------
selectGroceryCategory = Grocery
groceryDeliveryPinCode = 560038
groceryProduceName = FORTUNE
searchSpecificGroceryProduce = almonds

#-------travel page--------
selectTravelCategory = Travel

#-------Appliances page--------
selectAppliancesCategory = Appliances

#-------mobile page--------
selectmobilesCategory = Mobiles
selectMobileFromDefaultList = POCO
selectSpecificMobile =iphone
selectMobileBasedOnInput = Motorola Edge 50 Fusion

#-------fashion-menfootwear-all page--------
selectCategoryToHover = Fashion
selectSubMenuToHover = Men Footwear
selectSubMenuCategory = All

#-------electronics-gaming-all page--------
HoverOnElectronics = Electronics
selectSubMenuFromElectronicsDropdown = Gaming
selectCategoryFromElectronicsSubMenu = All

#-------cart page--------
cartpageDeliveryPincode = 560037

#--------------Mobile device input data-------------
selectMobilePlatform = android
#----------Android Mobile Input Data-----------
androidPlatformName = Android
androidDeviceName = emulator-5554
appiumServerURL = http://127.0.0.1:4723/wd/hub
androidApplicationPath = //Apps//com.flipkart.android-8.0.apk

#----------IOS Mobile Input Data-----------
iosPlatformName =
isoDeviceName =
iosDeviceName =
iosApplicationPath =
